version: 2
updates:
  - package-ecosystem: "docker" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    vendor: true
