inherit_from: .rubocop_todo.yml

inherit_gem:
  niftany: niftany_rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Style/RescueModifier:
  Exclude:
    - 'app/importers/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/models/concerns/null_object_pattern.rb'
    - 'app/components/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/component/models/concerns/null_object_pattern_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/component/importers/news_feed_item_importer_spec.rb'
    - 'spec/component/importers/unpaywall_publication_importer_spec.rb'
    - 'spec/component/models/activity_insight_publication_exporter_spec.rb'
    - 'spec/component/models/scholarsphere_file_version_uploads_spec.rb'
    - 'spec/component/models/scholarsphere_work_deposit_spec.rb'
    - 'spec/component/importers/activity_insight_importer_spec.rb'
    - 'spec/component/components/scholarsphere_deposit_form_component_spec.rb'
    - 'spec/integration/profiles/open_access_publications/edit_spec.rb'
    - 'spec/component/models/duplicate_publication_group_spec.rb'
    - 'spec/component/models/scholarsphere_pdf_file_version_spec.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/component/models/concerns/null_object_pattern_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/component/models/user_spec.rb'

Style/Semicolon:
  Exclude:
    - 'lib/tasks/database_data.rake'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/importers/activity_insight_importer.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/importers/activity_insight_importer.rb'

RSpec/PendingWithoutReason:
  Exclude:
    - 'spec/component/models/journal_spec.rb'
    - 'spec/component/models/organization_spec.rb'
    - 'spec/component/models/publisher_spec.rb'
    - 'spec/unit/decorators/authorship_decorator_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/api/v1/api_docs/organizations_spec.rb'
    - 'spec/requests/api/v1/api_docs/publications_spec.rb'
    - 'spec/requests/api/v1/api_docs/users_spec.rb'

RSpec/VariableName:
  Exclude:
    - 'spec/requests/api/v1/api_docs/organizations_spec.rb'
    - 'spec/requests/api/v1/api_docs/publications_spec.rb'
    - 'spec/requests/api/v1/api_docs/users_spec.rb'
