#!/bin/bash
# Continuous Integration build script.

set -e # Exit on any error
set -x # Echo each command

# Don't run the spring application preloader on ci
export DISABLE_SPRING=1

# Install ci-specific files
find . -name '*.ci' | rename -f 's/\.ci$//'

echo '========== Install Ruby ================================================'
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
rbenv install -s
rbenv version

echo '========== Gem Security ================================================='
bundle-audit update
bundle-audit check

echo '========== Install Gems ================================================='
bundle install --no-color --local

echo '========== Prepare Database ============================================='
bin/rake db:create:all
bin/rake db:migrate
bin/rake db:test:prepare

echo '========== Unit Tests ==================================================='
bin/rspec spec/unit

echo '========== Component Tests =============================================='
bin/rspec spec/component

echo '========== Integration Tests ============================================'
bin/rspec spec/integration

echo '========== Deploy To Staging ============================================'
current_revision=`git show | awk '/^commit / { print $2 }'`
bin/cap staging deploy -s branch=$current_revision

#echo '========== System Tests ================================================='
#bin/rspec --no-color spec.system
