x-web_env: &web_env
  environment:
      BUNDLE_DEFAULT_INSTALL_USES_PATH: vendor/bundle
      REDIS_PASSWORD: redispassword
      DEFAULT_URL_HOST: web
      APP_HOST: web
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: rmdrmd
      POSTGRES_USER: rmd
      POSTGRES_DB: rmd
      SETTINGS__activity_insight__username: ${SETTINGS__activity_insight__username}
      SETTINGS__activity_insight__password: ${SETTINGS__activity_insight__password}
      SETTINGS__activity_insight__export_url: ${SETTINGS__activity_insight__export_url}
      SETTINGS__activity_insight_s3_authorizer__api_key: ${SETTINGS__activity_insight_s3_authorizer__api_ke}
      SETTINGS__azure_ad_oauth__client_id: ${SETTINGS__azure_ad_oauth__client_id}
      SETTINGS__azure_ad_oauth__client_secret: ${SETTINGS__azure_ad_oauth__client_secret}
      SETTINGS__azure_ad_oauth__oauth_app_url: ${SETTINGS__azure_ad_oauth__oauth_app_url}
      SETTINGS__azure_ad_oauth__oauth_authorize_url: ${SETTINGS__azure_ad_oauth__oauth_authorize_url}
      SETTINGS__azure_ad_oauth__oauth_token_url: ${SETTINGS__azure_ad_oauth__oauth_token_url}
      SETTINGS__pure__api_key: ${SETTINGS__pure__api_key}
      SETTINGS__scholarsphere__client_key: ${SETTINGS__scholarsphere__client_key}
      SETTINGS__scholarsphere__endpoint: ${SETTINGS__scholarsphere__endpoint}
services:
  web:
    # Configure in .env
    user: "${UID}:${GID}"
    depends_on:
      - db
    tty: true
    stdin_open: true
    <<: *web_env
    build:
      context: .
      target: dev
    volumes:
    - bundle-data:/app/vendor/bundle
    - node-data:/app/node_modules
    - type: bind
      source: ./
      target: /app
    ports:
      - "3000:3000"
  db:
    environment:
      POSTGRES_PASSWORD: rmdrmd
      POSTGRES_USER: rmd
      POSTGRES_DB: rmd
    image: postgres:15.8
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

volumes:
  bundle-data:
  node-data:
  db-data:
