require 'rails_helper'
require 'support/authentication'
require 'support/capybara'
require 'support/database_cleaner'
require 'support/factory_bot'
require 'support/fixture'
require 'support/mail'
require 'support/fixture'
