common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: psu_research_metadata_development

test: &test
  <<: *common
  database: psu_research_metadata_test

