common: &common
  adapter: postgresql
  encoding: unicode
  host: db
  username: rmd
  password: rmd
  database: rmd
  port: 5432
  pool: 5

development:
  <<: *common
  database: rmd_development

test: &test
  <<: *common
  database: rmd_test