# Default Settings for RMD 
# Copy this file into `config/settings.local.yml` to override defaults
# To set environment specific defaults edit `config/settings/#{environment}.yml`
# To have environment specific overrides edit `config/settings/#{environment}.local.yml`
# Test environment does not read `config/settings.local.yml` settings for test should be put in `config/settings/test.yml`

lograge:
  enabled: false
  json: false

activity_insight:
  username:
  password:
  export_url:

activity_insight_s3_authorizer:
  api_key:

azure_ad_oauth:
  client_id:
  client_secret:
  oauth_app_url:
  oauth_token_url:
  oauth_authorize_url:

delayed_job:
  failure_threshold_minutes: 10
  upload_queue: scholarsphere-uploads

orcid:
  client_id:


postgres:
  database: psu_research_metadata 
  # username: nil 
  # password: nil 
  # port: nil
  # host: nil 

pure:
  api_key: 

scholarsphere:
  endpoint: 
  client_key: 


