#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'pure_downloader'

downloader = PureDownloader.new

if Dir.exists?(downloader.pure_pub_dir) && !Dir.empty?(downloader.pure_pub_dir)
  print 'Pure publication data is already present. Overwrite (Yn)?  '
  overwrite = gets.chomp

  if overwrite == 'Y'
    downloader.download_pure_pubs
  end

else
  FileUtils.mkdir_p downloader.data_dir
  FileUtils.mkdir_p downloader.pure_pub_dir

  downloader.download_pure_pubs
end
