#!/usr/bin/env ruby

require_relative './pure_downloader.rb'

downloader = PureDownloader.new

if Dir.exists?(downloader.pure_pub_dir) && ! Dir.empty?(downloader.pure_pub_dir)
  print "Pure publication data is already present. Overwrite (Yn)?  "
  overwrite = gets.chomp

  if overwrite == 'Y'
    downloader.download_pure_pubs
  end

else
  Dir.mkdir downloader.data_dir unless Dir.exists? downloader.data_dir
  Dir.mkdir downloader.pure_pub_dir unless Dir.exists? downloader.pure_pub_dir

  downloader.download_pure_pubs
end
