#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'pure_downloader'

downloader = PureDownloader.new

if File.exists? downloader.org_data_file
  print 'Organization data file already exists. Overwrite (Yn)?  '
  overwrite = gets.chomp

  if overwrite == 'Y'
    downloader.download_pure_orgs
  end
else
  FileUtils.mkdir_p downloader.data_dir

  downloader.download_pure_orgs
end
