action_mailer:
  perform_deliveries: false
  delivery_method: smtp
  raise_delivery_errors: true
  smtp_server: smtp.psu.edu
  smtp_port: 25
  default_url_options:
    host: metadata-qa.libraries.psu.edu
    protocol: https