pure:
  api_key: fake_api_key

activity_insight:
  username: test
  password: secret

scholarsphere:
  endpoint: "https://scholarsphere.test/api/"
  client_key:  "secret_key"

azure_ad_oauth:
  client_secret: test-azure-oauth-client-secret
  client_id: test-azure-oauth-client-id
  oauth_app_url: http://example.test
  oauth_token_url: /test/oauth2/v2.0/token
  oauth_authorize_url: /test/oauth2/v2.0/authorize

orcid:
  client_id: test
  client_secret: secret
